<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductSize;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Nike Air Max 270',
                'slug' => 'nike-air-max-270',
                'description' => null,
                'price' => 2800000.00,
                'sale_price' => null,
                'brand' => 'Nike',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Adidas Ultraboost 22',
                'slug' => 'adidas-ultraboost-22',
                'description' => null,
                'price' => 4500000.00,
                'sale_price' => null,
                'brand' => 'Adidas',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 3,
                'category_id' => 2,
                'name' => 'Converse Chuck Taylor',
                'slug' => 'converse-chuck-taylor',
                'description' => null,
                'price' => 950000.00,
                'sale_price' => null,
                'brand' => 'Converse',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 4,
                'category_id' => 2,
                'name' => 'Puma RS-X',
                'slug' => 'puma-rs-x',
                'description' => null,
                'price' => 2300000.00,
                'sale_price' => null,
                'brand' => 'Puma',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Nike Air Force 1',
                'slug' => 'nike-air-force-1',
                'description' => null,
                'price' => 2600000.00,
                'sale_price' => null,
                'brand' => 'Nike',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 6,
                'category_id' => 2,
                'name' => 'Adidas Stan Smith',
                'slug' => 'adidas-stan-smith',
                'description' => null,
                'price' => 1800000.00,
                'sale_price' => null,
                'brand' => 'Adidas',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'name' => 'Vans Old Skool',
                'slug' => 'vans-old-skool',
                'description' => null,
                'price' => 1600000.00,
                'sale_price' => null,
                'brand' => 'Vans',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 8,
                'category_id' => 1,
                'name' => 'Nike Air Jordan 1 Mid',
                'slug' => 'nike-air-jordan-1-mid',
                'description' => null,
                'price' => 3200000.00,
                'sale_price' => null,
                'brand' => 'Nike',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 9,
                'category_id' => 3,
                'name' => 'Puma Suede Classic',
                'slug' => 'puma-suede-classic',
                'description' => null,
                'price' => 1100000.00,
                'sale_price' => null,
                'brand' => 'Puma',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
            [
                'id' => 10,
                'category_id' => 3,
                'name' => 'Converse One Star',
                'slug' => 'converse-one-star',
                'description' => null,
                'price' => 750000.00,
                'sale_price' => null,
                'brand' => 'Converse',
                'image' => '',
                'images' => null,
                'color' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'average_cost' => 0.00,
                'profit_margin' => 0.00,
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::create($productData);
            
            // Tạo 11 size từ 35 đến 45 với quantity = 0
            for ($size = 35; $size <= 45; $size++) {
                ProductSize::create([
                    'product_id' => $product->id,
                    'size' => (string)$size,
                    'quantity' => 0,
                    'total_imported' => 0,
                    'total_sold' => 0,
                    'average_cost_per_size' => 0.00,
                ]);
            }
        }
    }
}
