<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Giày Nam
            [
                'category_id' => 1,
                'name' => 'Nike Air Max 270',
                'slug' => 'nike-air-max-270',
                'description' => 'Giày thể thao Nike Air Max 270 với thiết kế hiện đại, đệm khí thoải mái',
                'price' => 3100000,
                'sale_price' => 2490000,
                'brand' => 'Nike',
                'image' => 'nike-air-max-270.jpg',
                'sizes' => json_encode(['39', '40', '41', '42', '43']),
                'color' => 'Xanh đen',
                'stock' => 50,
                'is_featured' => true,
                'is_new' => true,
                'rating' => 4.5,
                'reviews_count' => 128,
            ],
            [
                'category_id' => 1,
                'name' => 'Adidas Ultraboost 22',
                'slug' => 'adidas-ultraboost-22',
                'description' => 'Adidas Ultraboost 22 với công nghệ đệm Boost tiên tiến',
                'price' => 4200000,
                'sale_price' => 3360000,
                'brand' => 'Adidas',
                'image' => 'adidas-ultraboost-22.jpg',
                'sizes' => json_encode(['39', '40', '41', '42', '43', '44']),
                'color' => 'Trắng xám',
                'stock' => 35,
                'is_featured' => true,
                'is_new' => true,
                'rating' => 4.8,
                'reviews_count' => 256,
            ],
            [
                'category_id' => 1,
                'name' => 'Puma RS-X',
                'slug' => 'puma-rs-x',
                'description' => 'Puma RS-X phong cách retro hiện đại',
                'price' => 2500000,
                'sale_price' => 2000000,
                'brand' => 'Puma',
                'image' => 'puma-rs-x.jpg',
                'sizes' => json_encode(['39', '40', '41', '42', '43']),
                'color' => 'Đa sắc',
                'stock' => 40,
                'is_featured' => false,
                'is_new' => true,
                'rating' => 4.3,
                'reviews_count' => 89,
            ],
            [
                'category_id' => 1,
                'name' => 'New Balance 574',
                'slug' => 'new-balance-574',
                'description' => 'New Balance 574 classic, bền bỉ và thoải mái',
                'price' => 2800000,
                'sale_price' => 2240000,
                'brand' => 'New Balance',
                'image' => 'new-balance-574.jpg',
                'sizes' => json_encode(['39', '40', '41', '42', '43']),
                'color' => 'Xám xanh',
                'stock' => 45,
                'is_featured' => false,
                'is_new' => true,
                'rating' => 4.6,
                'reviews_count' => 145,
            ],
            
            // Giày Nữ
            [
                'category_id' => 2,
                'name' => 'Nike Air Force 1 Low',
                'slug' => 'nike-air-force-1-low',
                'description' => 'Giày Nike Air Force 1 Low phiên bản nữ',
                'price' => 2900000,
                'sale_price' => 2320000,
                'brand' => 'Nike',
                'image' => 'nike-af1-low.jpg',
                'sizes' => json_encode(['35', '36', '37', '38', '39', '40']),
                'color' => 'Trắng tiền',
                'stock' => 60,
                'is_featured' => true,
                'is_new' => true,
                'rating' => 4.7,
                'reviews_count' => 189,
            ],
            [
                'category_id' => 2,
                'name' => 'Adidas Stan Smith',
                'slug' => 'adidas-stan-smith',
                'description' => 'Adidas Stan Smith phiên bản nữ, thiết kế tiến',
                'price' => 2400000,
                'sale_price' => 1920000,
                'brand' => 'Adidas',
                'image' => 'adidas-stan-smith.jpg',
                'sizes' => json_encode(['35', '36', '37', '38', '39']),
                'color' => 'Trắng xanh',
                'stock' => 55,
                'is_featured' => false,
                'is_new' => true,
                'rating' => 4.5,
                'reviews_count' => 167,
            ],
            [
                'category_id' => 2,
                'name' => 'Vans Old Skool',
                'slug' => 'vans-old-skool',
                'description' => 'Vans Old Skool phiên bản nữ, phong cách streetwear',
                'price' => 1800000,
                'sale_price' => 1440000,
                'brand' => 'Vans',
                'image' => 'vans-old-skool.jpg',
                'sizes' => json_encode(['35', '36', '37', '38', '39']),
                'color' => 'Đen trắng',
                'stock' => 70,
                'is_featured' => false,
                'is_new' => false,
                'rating' => 4.4,
                'reviews_count' => 203,
            ],
            [
                'category_id' => 2,
                'name' => 'Converse Chuck Taylor All Star',
                'slug' => 'converse-chuck-taylor',
                'description' => 'Giày Converse Chuck Taylor All Star classic',
                'price' => 1500000,
                'sale_price' => 1200000,
                'brand' => 'Converse',
                'image' => 'converse-chuck-taylor.jpg',
                'sizes' => json_encode(['35', '36', '37', '38', '39', '40']),
                'color' => 'Trắng',
                'stock' => 80,
                'is_featured' => false,
                'is_new' => false,
                'rating' => 4.6,
                'reviews_count' => 312,
            ],

            // Giày Trẻ Em
            [
                'category_id' => 3,
                'name' => 'Nike Air Max SC Kids',
                'slug' => 'nike-air-max-sc-kids',
                'description' => 'Giày Nike Air Max dành cho trẻ em',
                'price' => 1800000,
                'sale_price' => 1440000,
                'brand' => 'Nike',
                'image' => 'nike-air-max-kids.jpg',
                'sizes' => json_encode(['28', '29', '30', '31', '32', '33', '34']),
                'color' => 'Hồng xanh',
                'stock' => 45,
                'is_featured' => false,
                'is_new' => true,
                'rating' => 4.5,
                'reviews_count' => 78,
            ],
            [
                'category_id' => 3,
                'name' => 'Adidas Superstar Kids',
                'slug' => 'adidas-superstar-kids',
                'description' => 'Adidas Superstar phiên bản trẻ em',
                'price' => 1600000,
                'sale_price' => 1280000,
                'brand' => 'Adidas',
                'image' => 'adidas-superstar-kids.jpg',
                'sizes' => json_encode(['28', '29', '30', '31', '32', '33']),
                'color' => 'Trắng đen',
                'stock' => 50,
                'is_featured' => false,
                'is_new' => true,
                'rating' => 4.6,
                'reviews_count' => 92,
            ],

            // Thêm 6 sản phẩm nữa để đủ 8 sản phẩm hiển thị
            [
                'category_id' => 1,
                'name' => 'Asics Gel-Kayano 29',
                'slug' => 'asics-gel-kayano-29',
                'description' => 'Asics Gel-Kayano 29 dành cho chạy bộ',
                'price' => 3800000,
                'sale_price' => 3040000,
                'brand' => 'Asics',
                'image' => 'asics-gel-kayano.jpg',
                'sizes' => json_encode(['39', '40', '41', '42', '43']),
                'color' => 'Xanh dương cam',
                'stock' => 30,
                'is_featured' => true,
                'is_new' => true,
                'rating' => 4.7,
                'reviews_count' => 156,
            ],
            [
                'category_id' => 1,
                'name' => 'Reebok Classic Leather',
                'slug' => 'reebok-classic-leather',
                'description' => 'Reebok Classic Leather phong cách retro',
                'price' => 2200000,
                'sale_price' => 1760000,
                'brand' => 'Reebok',
                'image' => 'reebok-classic.jpg',
                'sizes' => json_encode(['39', '40', '41', '42', '43']),
                'color' => 'Trắng',
                'stock' => 40,
                'is_featured' => false,
                'is_new' => false,
                'rating' => 4.3,
                'reviews_count' => 98,
            ],
            [
                'category_id' => 2,
                'name' => 'Puma Cali Sport',
                'slug' => 'puma-cali-sport',
                'description' => 'Puma Cali Sport dành cho nữ, phong cách California',
                'price' => 2300000,
                'sale_price' => 1840000,
                'brand' => 'Puma',
                'image' => 'puma-cali-sport.jpg',
                'sizes' => json_encode(['35', '36', '37', '38', '39']),
                'color' => 'Trắng hồng',
                'stock' => 48,
                'is_featured' => false,
                'is_new' => true,
                'rating' => 4.4,
                'reviews_count' => 134,
            ],
            [
                'category_id' => 2,
                'name' => 'New Balance 327',
                'slug' => 'new-balance-327-women',
                'description' => 'New Balance 327 phiên bản nữ, thiết kế retro',
                'price' => 2600000,
                'sale_price' => 2080000,
                'brand' => 'New Balance',
                'image' => 'new-balance-327.jpg',
                'sizes' => json_encode(['35', '36', '37', '38', '39']),
                'color' => 'Xanh rêu cam',
                'stock' => 42,
                'is_featured' => false,
                'is_new' => true,
                'rating' => 4.5,
                'reviews_count' => 112,
            ],
        ];

        foreach ($products as $product) {
            \App\Models\Product::create($product);
        }
    }
}
