<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class PumaProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['category_id' => 1, 'name' => 'Puma RS-X', 'slug' => 'puma-rs-x', 'description' => 'Puma RS-X với thiết kế chunky retro futuristic', 'price' => 2700000, 'sale_price' => 2160000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_10.jpg', 'images' => json_encode(['image/puma/Puma_train_10.jpg', 'image/puma/Puma_train_11.jpg', 'image/puma/Puma_train_12.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43', '44']), 'color' => 'Đa sắc', 'stock' => 52, 'is_featured' => true, 'is_new' => true, 'rating' => 4.6, 'reviews_count' => 189],
            ['category_id' => 2, 'name' => 'Puma Cali Sport', 'slug' => 'puma-cali-sport', 'description' => 'Puma Cali Sport phong cách California streetwear', 'price' => 2300000, 'sale_price' => 1840000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_15.jpg', 'images' => json_encode(['image/puma/Puma_train_15.jpg', 'image/puma/Puma_train_16.jpg', 'image/puma/Puma_train_17.jpg']), 'sizes' => json_encode(['35', '36', '37', '38', '39', '40']), 'color' => 'Trắng hồng', 'stock' => 64, 'is_featured' => true, 'is_new' => false, 'rating' => 4.7, 'reviews_count' => 267],
            ['category_id' => 1, 'name' => 'Puma Suede Classic', 'slug' => 'puma-suede-classic', 'description' => 'Puma Suede Classic với chất liệu da lộn cao cấp', 'price' => 2100000, 'sale_price' => 1680000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_20.jpg', 'images' => json_encode(['image/puma/Puma_train_20.jpg', 'image/puma/Puma_train_21.jpg', 'image/puma/Puma_train_22.jpg', 'image/puma/Puma_train_23.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43']), 'color' => 'Xanh navy', 'stock' => 78, 'is_featured' => false, 'is_new' => false, 'rating' => 4.8, 'reviews_count' => 345],
            ['category_id' => 1, 'name' => 'Puma Future Rider', 'slug' => 'puma-future-rider', 'description' => 'Puma Future Rider với công nghệ đệm Rider Foam', 'price' => 2500000, 'sale_price' => 2000000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_25.jpg', 'images' => json_encode(['image/puma/Puma_train_25.jpg', 'image/puma/Puma_train_26.jpg', 'image/puma/Puma_train_27.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43']), 'color' => 'Xám cam', 'stock' => 56, 'is_featured' => false, 'is_new' => true, 'rating' => 4.5, 'reviews_count' => 178],
            ['category_id' => 2, 'name' => 'Puma Mayze', 'slug' => 'puma-mayze', 'description' => 'Puma Mayze với đế platform chunky thời trang', 'price' => 2400000, 'sale_price' => 1920000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_30.jpg', 'images' => json_encode(['image/puma/Puma_train_30.jpg', 'image/puma/Puma_train_31.jpg', 'image/puma/Puma_train_32.jpg']), 'sizes' => json_encode(['35', '36', '37', '38', '39', '40']), 'color' => 'Trắng', 'stock' => 61, 'is_featured' => true, 'is_new' => true, 'rating' => 4.6, 'reviews_count' => 234],
            ['category_id' => 1, 'name' => 'Puma Velocity Nitro', 'slug' => 'puma-velocity-nitro', 'description' => 'Puma Velocity Nitro giày chạy bộ với đệm Nitro', 'price' => 3200000, 'sale_price' => 2560000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_35.jpg', 'images' => json_encode(['image/puma/Puma_train_35.jpg', 'image/puma/Puma_train_36.jpg', 'image/puma/Puma_train_37.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43', '44']), 'color' => 'Xanh vàng', 'stock' => 43, 'is_featured' => false, 'is_new' => true, 'rating' => 4.7, 'reviews_count' => 156],
            ['category_id' => 1, 'name' => 'Puma Slipstream', 'slug' => 'puma-slipstream', 'description' => 'Puma Slipstream với thiết kế basketball vintage', 'price' => 2600000, 'sale_price' => 2080000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_40.jpg', 'images' => json_encode(['image/puma/Puma_train_40.jpg', 'image/puma/Puma_train_41.jpg', 'image/puma/Puma_train_42.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43']), 'color' => 'Trắng xanh', 'stock' => 58, 'is_featured' => false, 'is_new' => false, 'rating' => 4.4, 'reviews_count' => 198],
            ['category_id' => 2, 'name' => 'Puma Smash Platform', 'slug' => 'puma-smash-platform', 'description' => 'Puma Smash Platform với đế cao thời trang', 'price' => 2200000, 'sale_price' => 1760000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_45.jpg', 'images' => json_encode(['image/puma/Puma_train_45.jpg', 'image/puma/Puma_train_46.jpg', 'image/puma/Puma_train_47.jpg']), 'sizes' => json_encode(['35', '36', '37', '38', '39']), 'color' => 'Đen trắng', 'stock' => 67, 'is_featured' => false, 'is_new' => false, 'rating' => 4.3, 'reviews_count' => 213],
            ['category_id' => 1, 'name' => 'Puma Ultra Ultimate', 'slug' => 'puma-ultra-ultimate', 'description' => 'Puma Ultra Ultimate giày bóng đá tốc độ', 'price' => 3800000, 'sale_price' => 3040000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_50.jpg', 'images' => json_encode(['image/puma/Puma_train_50.jpg', 'image/puma/Puma_train_51.jpg', 'image/puma/Puma_train_52.jpg', 'image/puma/Puma_train_53.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43']), 'color' => 'Vàng đen', 'stock' => 34, 'is_featured' => true, 'is_new' => true, 'rating' => 4.8, 'reviews_count' => 287],
            ['category_id' => 1, 'name' => 'Puma Deviate Nitro', 'slug' => 'puma-deviate-nitro', 'description' => 'Puma Deviate Nitro giày marathon carbon plate', 'price' => 4200000, 'sale_price' => 3360000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_55.jpg', 'images' => json_encode(['image/puma/Puma_train_55.jpg', 'image/puma/Puma_train_56.jpg', 'image/puma/Puma_train_57.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43']), 'color' => 'Cam đen', 'stock' => 28, 'is_featured' => true, 'is_new' => true, 'rating' => 4.9, 'reviews_count' => 312],
            ['category_id' => 2, 'name' => 'Puma Vikky Platform', 'slug' => 'puma-vikky-platform', 'description' => 'Puma Vikky Platform với thiết kế platform trendy', 'price' => 2000000, 'sale_price' => 1600000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_60.jpg', 'images' => json_encode(['image/puma/Puma_train_60.jpg', 'image/puma/Puma_train_61.jpg', 'image/puma/Puma_train_62.jpg']), 'sizes' => json_encode(['35', '36', '37', '38', '39', '40']), 'color' => 'Xám', 'stock' => 72, 'is_featured' => false, 'is_new' => false, 'rating' => 4.4, 'reviews_count' => 176],
            ['category_id' => 1, 'name' => 'Puma Disc Blaze', 'slug' => 'puma-disc-blaze', 'description' => 'Puma Disc Blaze với hệ thống khóa Disc độc đáo', 'price' => 2900000, 'sale_price' => 2320000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_65.jpg', 'images' => json_encode(['image/puma/Puma_train_65.jpg', 'image/puma/Puma_train_66.jpg', 'image/puma/Puma_train_67.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43']), 'color' => 'Xanh dương', 'stock' => 47, 'is_featured' => false, 'is_new' => true, 'rating' => 4.5, 'reviews_count' => 154],
            ['category_id' => 3, 'name' => 'Puma X-Ray Kids', 'slug' => 'puma-x-ray-kids', 'description' => 'Puma X-Ray dành cho trẻ em với design năng động', 'price' => 1500000, 'sale_price' => 1200000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_70.jpg', 'images' => json_encode(['image/puma/Puma_train_70.jpg', 'image/puma/Puma_train_71.jpg', 'image/puma/Puma_train_72.jpg']), 'sizes' => json_encode(['28', '29', '30', '31', '32', '33', '34']), 'color' => 'Đỏ xanh', 'stock' => 85, 'is_featured' => false, 'is_new' => true, 'rating' => 4.6, 'reviews_count' => 145],
            ['category_id' => 1, 'name' => 'Puma LQD Cell Optic', 'slug' => 'puma-lqd-cell-optic', 'description' => 'Puma LQD Cell Optic với công nghệ đệm Cell', 'price' => 2800000, 'sale_price' => 2240000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_75.jpg', 'images' => json_encode(['image/puma/Puma_train_75.jpg', 'image/puma/Puma_train_76.jpg', 'image/puma/Puma_train_77.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43', '44']), 'color' => 'Xám neon', 'stock' => 51, 'is_featured' => false, 'is_new' => false, 'rating' => 4.3, 'reviews_count' => 167],
            ['category_id' => 2, 'name' => 'Puma Basket Platform', 'slug' => 'puma-basket-platform', 'description' => 'Puma Basket Platform metallic với lớp finish bóng', 'price' => 2350000, 'sale_price' => 1880000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_80.jpg', 'images' => json_encode(['image/puma/Puma_train_80.jpg', 'image/puma/Puma_train_81.jpg', 'image/puma/Puma_train_82.jpg']), 'sizes' => json_encode(['35', '36', '37', '38', '39', '40']), 'color' => 'Vàng gold', 'stock' => 44, 'is_featured' => true, 'is_new' => true, 'rating' => 4.7, 'reviews_count' => 223],
            ['category_id' => 1, 'name' => 'Puma Ignite Limitless', 'slug' => 'puma-ignite-limitless', 'description' => 'Puma Ignite Limitless cho tập gym và training', 'price' => 2600000, 'sale_price' => 2080000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_85.jpg', 'images' => json_encode(['image/puma/Puma_train_85.jpg', 'image/puma/Puma_train_86.jpg', 'image/puma/Puma_train_87.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43']), 'color' => 'Đen đỏ', 'stock' => 59, 'is_featured' => false, 'is_new' => false, 'rating' => 4.5, 'reviews_count' => 189],
            ['category_id' => 1, 'name' => 'Puma Thunder Spectra', 'slug' => 'puma-thunder-spectra', 'description' => 'Puma Thunder Spectra với thiết kế chunky bold', 'price' => 2700000, 'sale_price' => 2160000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_90.jpg', 'images' => json_encode(['image/puma/Puma_train_90.jpg', 'image/puma/Puma_train_91.jpg', 'image/puma/Puma_train_92.jpg', 'image/puma/Puma_train_93.jpg']), 'sizes' => json_encode(['39', '40', '41', '42', '43', '44']), 'color' => 'Đa sắc', 'stock' => 41, 'is_featured' => false, 'is_new' => true, 'rating' => 4.6, 'reviews_count' => 201],
            ['category_id' => 2, 'name' => 'Puma Softride Sophia', 'slug' => 'puma-softride-sophia', 'description' => 'Puma Softride Sophia với đệm êm ái tối đa', 'price' => 2100000, 'sale_price' => 1680000, 'brand' => 'Puma', 'image' => 'image/puma/Puma_train_95.jpg', 'images' => json_encode(['image/puma/Puma_train_95.jpg', 'image/puma/Puma_train_96.jpg', 'image/puma/Puma_train_97.jpg']), 'sizes' => json_encode(['35', '36', '37', '38', '39']), 'color' => 'Hồng pastel', 'stock' => 63, 'is_featured' => false, 'is_new' => true, 'rating' => 4.4, 'reviews_count' => 178],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
